Adj1=input("Enter an adjective  :")
Nat=input("Enter a nationality  :")
per=input("Enter a person  :")
N1=input("Enter a noun  :")
Adj2=input("Enter an adjective  :")
N2=input("enter a noun  :")
Adj3=input("Enter an adjective  :")
Adj4=input("Enter an adjective  :")
Pln=input("Enter a plural noun  :")
N3=input("Enter a noun  :")
Num1=input("Enter a number  :")
Shape=input("Enter a shape  :")
Food1=input("Enter a food  :")
Food2=input("Enter a food  :")
Num2=input("Enter a number  :")

print("Pizza was invented by a " + Adj1 , Nat + " chef named " + per + ".To make a pizza,you need to take a lump of ")
print(N1 + " and make a thin ,round " + Adj2 +" "+ N2 + ".Then you cover it with " + Adj3)
print("sauce," + Adj4 + " cheese,and fresh")
print("chopped " + Pln + ".Next you have to bake it in a very")
print("hot " + N3 + ".When it is done,cut it into " + Num1 )
print(Shape + ". Some kids like " + Food1 + " Pizza the ")
print("best,but my favorite is the " + Food2 + " pizza.if i could,I ")
print("would eat pizza " + Num2 + " times a day!")
