import turtle
turtle.bgcolor("pink")
t = turtle.Turtle()
t.shape("turtle")
t.fillcolor("blue")
t.begin_fill()
for i in range(4):
    t.forward(150)
    t.right(-120)
t.end_fill()
t.penup()
t.setposition(-200,-300)
t.pendown()
t.pencolor("Cyan")
t.fillcolor("purple")
t.begin_fill()
t.circle(50)
t.end_fill()
turtle.done()
