import turtle
t=turtle.Turtle()
turtle.title("Look at the title")
turtle.bgcolor("black")
t.shape("turtle")
t.fillcolor("HotPink")
t.pencolor("Aquamarine")
t.shapesize(3)
t.speed(1)
t.forward(200)
t.right(90)
t.speed(300)
t.forward(100)
turtle.done()
